### ISSUE TITLE
有中文版本没？

### ISSUE THREAD

**Issue by EchoZuo** [ChenYilong/iOS10AdaptationTips#3]
有中文版本没？😂

**Comment by BaihaoTian** [comment]
https://github.com/BaihaoTian/iOS10AdaptationTips-chineseEdition 我翻译的

**Comment by EchoZuo** [comment]
@BaihaoTian 好的，谢谢。

**Comment by ChenYilong** [comment]
@BaihaoTian 谢谢你的翻译，同时也欢迎提PR

**Comment by BaihaoTian** [comment]
@ChenYilong  已提PR  你看看
